name: Datafy Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build:
    runs-on: datafy-16-cores
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: build
        run: make datafy-build

  unit-tests:
    needs: [ build ]
    runs-on: datafy-16-cores
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: test
        run: make datafy-test

  acc-tests:
    needs: [ build ]
    runs-on: datafy-16-cores
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "us-west-2"
          role-to-assume: ${{ secrets.DEVELOPMENT_AWS_ROLE_ARN }}
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: 1.15.5
          terraform_wrapper: false
      - name: testacc
        run: make datafy-testacc

  importlint:
    name: Import lint
    needs: [ build ]
    runs-on: datafy-16-cores
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./.ci/tools/go.mod
      - run: cd .ci/tools && go install github.com/pavius/impi/cmd/impi
      - run: impi --local . --scheme stdThirdPartyLocal ./...

  terraform_providers_schema:
    name: Terraform providers schema
    needs: [ build ]
    runs-on: datafy-16-cores
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: build
        run: make go-build
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: 1.15.5
          terraform_wrapper: false
      - name: terraform init
        run: |
          # We need a file to initialize the provider
          echo 'data "aws_partition" "example" {}' > example.tf
          terraform init -plugin-dir terraform-plugin-dir
      - name: terraform providers schema
        run: |
          mkdir terraform-providers-schema
          terraform providers schema -json > terraform-providers-schema/schema.json

  markdown-lint:
    name: Markdown lint
    runs-on: datafy-16-cores
    steps:
      - uses: actions/checkout@v6
      - uses: avto-dev/markdown-lint@v1
        with:
          args: "."
          ignore: "./docs ./website/docs ./CHANGELOG.md ./internal/service/cloudformation/test-fixtures/examplecompany-exampleservice-exampleresource/docs"

  misspell:
    name: Misspell
    runs-on: datafy-16-cores
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./.ci/tools/go.mod
      - run: cd .ci/tools && go install github.com/client9/misspell/cmd/misspell
      - run: make go-misspell
